@0xc78b28401862d00d; # unique file ID, generated by `capnp id`

interface LogSink {
  log @0 (snowflakeId :UInt64, machineId :UInt64, schema :UInt64, payload :AnyPointer) -> ();
}

interface LogSource {
  get @0 (snowflakeId :UInt64, machineId :UInt64, schema :UInt64, verify :Bool) -> (payload :Data);
}

struct LogEntry {
  snowflakeId @0 :UInt64;
  machineId @1 :UInt64;
  schema @2 :UInt64;
  payload @3 :AnyPointer;
}