@0xc78b28401862d00d; # unique file ID, generated by `capnp id`

interface LogSink {
  log @0 (snowflakeId :UInt64, machineId :UInt64, schema :UInt64, data :Data) -> ();
}

interface LogSource {
  get @0 (snowflakeId :UInt64, machineId :UInt64, schema :UInt64, verify :Bool) -> (payload :Data);
}
